//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AnalyticEventNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AnalyticEventNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.AnalyticEventNames", typeof(AnalyticEventNames).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AboutPageStarted.
        /// </summary>
        public static string AboutPageStarted {
            get {
                return ResourceManager.GetString("AboutPageStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Closed.
        /// </summary>
        public static string AppClosed {
            get {
                return ResourceManager.GetString("AppClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Opened.
        /// </summary>
        public static string AppOpened {
            get {
                return ResourceManager.GetString("AppOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateAccountPageStarted.
        /// </summary>
        public static string CreateAccountPageStarted {
            get {
                return ResourceManager.GetString("CreateAccountPageStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditProfilePageStarted.
        /// </summary>
        public static string EditProfilePageStarted {
            get {
                return ResourceManager.GetString("EditProfilePageStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forcefield: Exception.
        /// </summary>
        public static string ExceptionForcefield {
            get {
                return ResourceManager.GetString("ExceptionForcefield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebViewFragment: NullPointerException.
        /// </summary>
        public static string ExceptionWebView {
            get {
                return ResourceManager.GetString("ExceptionWebView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForgotPasswordPageStarted.
        /// </summary>
        public static string ForgotPasswordPageStarted {
            get {
                return ResourceManager.GetString("ForgotPasswordPageStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GCM Message opened after 15 minutes.
        /// </summary>
        public static string GcmMessageOpenedAfter15m {
            get {
                return ResourceManager.GetString("GcmMessageOpenedAfter15m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GCM Message opened within 15 minutes.
        /// </summary>
        public static string GcmMessageOpenedWithin15m {
            get {
                return ResourceManager.GetString("GcmMessageOpenedWithin15m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GCM Message Received.
        /// </summary>
        public static string GcmMessageReceived {
            get {
                return ResourceManager.GetString("GcmMessageReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HomePageStarted.
        /// </summary>
        public static string HomePageStarted {
            get {
                return ResourceManager.GetString("HomePageStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LearnPageStarted.
        /// </summary>
        public static string LearnPageStarted {
            get {
                return ResourceManager.GetString("LearnPageStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginPageStarted.
        /// </summary>
        public static string LoginPageStarted {
            get {
                return ResourceManager.GetString("LoginPageStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessagesPageStarted.
        /// </summary>
        public static string MessagesPageStarted {
            get {
                return ResourceManager.GetString("MessagesPageStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrimMemory level: .
        /// </summary>
        public static string PrefixForTrimMemoryLevel {
            get {
                return ResourceManager.GetString("PrefixForTrimMemoryLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProgressScreenDiaryViewStarted.
        /// </summary>
        public static string ProgressScreenDiaryViewStarted {
            get {
                return ResourceManager.GetString("ProgressScreenDiaryViewStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProgressScreenMedicationViewStarted.
        /// </summary>
        public static string ProgressScreenMedicationViewStarted {
            get {
                return ResourceManager.GetString("ProgressScreenMedicationViewStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScheduleItemEditPageStarted.
        /// </summary>
        public static string ScheduleItemEditPageStarted {
            get {
                return ResourceManager.GetString("ScheduleItemEditPageStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScheduleMonthViewStarted.
        /// </summary>
        public static string ScheduleMonthViewStarted {
            get {
                return ResourceManager.GetString("ScheduleMonthViewStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScheduleSetupPageStarted.
        /// </summary>
        public static string ScheduleSetupPageStarted {
            get {
                return ResourceManager.GetString("ScheduleSetupPageStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScheduleWeekViewStarted.
        /// </summary>
        public static string ScheduleWeekViewStarted {
            get {
                return ResourceManager.GetString("ScheduleWeekViewStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SettingsPageStarted.
        /// </summary>
        public static string SettingsPageStarted {
            get {
                return ResourceManager.GetString("SettingsPageStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opened.
        /// </summary>
        public static string SuffixForOpened {
            get {
                return ResourceManager.GetString("SuffixForOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to viewed for less than 10 s.
        /// </summary>
        public static string ViewedFor10s {
            get {
                return ResourceManager.GetString("ViewedFor10s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to viewed for 61-600 s.
        /// </summary>
        public static string ViewedFor600s {
            get {
                return ResourceManager.GetString("ViewedFor600s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to viewed for 11-60 s.
        /// </summary>
        public static string ViewedFor60s {
            get {
                return ResourceManager.GetString("ViewedFor60s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to viewed for more than 601 s.
        /// </summary>
        public static string ViewedForLong {
            get {
                return ResourceManager.GetString("ViewedForLong", resourceCulture);
            }
        }
    }
}
